### ISSUE TITLE
TypeError: Cannot read property 'toBuffer' of undefined

### ISSUE THREAD

**Issue by NoR3s** [bitcoinjs/bitcoinjs-message#13]
Hello,

This is my code i try to sign and get this error

TypeError: Cannot read property 'toBuffer' of undefined

``` js
var bitcoin = require('bitcoinjs-lib') // v3.x.x
var bitcoinMessage = require('bitcoinjs-message')

var keyPair = bitcoin.ECPair.fromWIF('5KYZdUEo39z3FPrtuX2QbbwGnNP5zTd7yyr2SC1j299sBCnWjss')
var privateKey = keyPair.d.toBuffer(32)
var message = 'This is an example of a signed message.'

var signature = bitcoinMessage.sign(message, privateKey, keyPair.compressed)
console.log(signature.toString('base64'))
```

**Comment by dabura667** [comment]
v3.x.x

current version of bitcoinjs-lib is v4.0.1

**Comment by NoR3s** [comment]
Hi im using the latest version and i still have this error

**Comment by dcousens** [comment]
@NoR3s that is the problem,  you are using the `^3.0.0` API,  where `^4.0.0` is different.
Please see the CHANGELOG.

**Comment by vivekteega** [comment]
Hey guys, I understand **toBuffer** has been changed in the new version of the library. 

But what is the solution for this? I really want to use bitcoinjs-lib to sign messages. I would really appreciate if someone could help me out here 
Thanks

**Comment by vivekteega** [comment]
haha I understood. I'm just using the older version and its working fine :)
