### ISSUE TITLE
Crashes out if signature is wrong

### ISSUE THREAD

**Issue by mmvphil** [bitcoinjs/bitcoinjs-message#14]
If it is the correct sig then it returns TRUE and all is good However..

if not...it bombs out crashing node...
/node_modules/bitcoinjs-message/index.js:23
  if (buffer.length !== 65) throw new Error('Invalid signature length')
              ^
Error: Invalid signature length
----------------------------------
var address = '1HZwkjkeaoZfTSaJxDw6aKkxp45agDiEzN'
var signature = 'HJgLQlDWLyb1Ef8bQKEISzFbDAKctIlaqOpGbrk3YVtRsjmC61lpE5ErkPRUFtDKtx98vHFGUWlFhsh3DiW6N0rE'
var message = 'This is an example of a signed message.'
console.log(bitcoinMessage.verify(message, address, signature))

**Comment by mmvphil** [comment]
Actually this should not be close VERIFYING MESSAGE returning other than true CRASHES.
instead of returning false.. like if you change the public signing address or anything .. this sucks really/node_modules/bs58check/base.js:41
    if (!payload) throw new Error('Invalid checksum')
                  ^

Error: Invalid checksum
    at Object.decode (/home/quic etc etc

Im so frustrated i have to USE  a php cli call to verify addresses.

THIS IS NOT COOL..

**Comment by dcousens** [comment]
@mmvphil are you saying that the garbage, malformed inputs you are providing,  are throwing errors not `return `false`?
Why would you expect them to work at all?

Sanitize your inputs.

**Comment by mmvphil** [comment]
Yes , how would I go about sanitizing it?
