### ISSUE TITLE
Crashes node app

### ISSUE THREAD

**Issue by mmvphil** [bitcoinjs/bitcoinjs-message#15]
Sorry issues/14 should not be closed

so many times if it does not return true it hallts the app. it should just return false
if it doesnt like the input  pub address or sig or message.. not just FKN CRASH

**Comment by mmvphil** [comment]
verifymsg = function (msg,pubaddr,signature){
 return bitcoinMessage.verify(msg, pubaddr, signature)
}

IF msg pubaddress or sig is wrong IN ANY WAY just return FALSE I.E. Not verified
or is there a way to call the function and not have it completely ruin the day?

**Comment by mmvphil** [comment]
i have been struggling with this tyring to right a Lightning app and I need to verify messages as part of my security protocol ..  If I cant do it within nodejs i have to literally call an external php verify msg proram via cli.. and that plain stinks.. can anybody help me?

**Comment by dcousens** [comment]
Please use https://github.com/bitcoinjs/bitcoinjs-message/issues/14#issuecomment-415305971 for any comments RE that issue.  No need for two issues now.
