### ISSUE TITLE
README.md example uses uncompressed key for p2wpkh and p2sh(p2wpkh) signing.

### ISSUE THREAD

**Issue by jmacxx** [bitcoinjs/bitcoinjs-message#21]
The example code in README.md uses WIF '5KYZdUEo39z3FPrtuX2QbbwGnNP5zTd7yyr2SC1j299sBCnWjss' to generate message signatures segwitType: 'p2sh(p2wpkh)' and segwitType: 'p2wpkh'.  Segwit does not support uncompressed keys.    I think that the example should use a valid scenario.

**Comment by junderw** [comment]
Fixed in 07c1984
