### ISSUE TITLE
Request: allow bitcoinjs-message to use a bitcoinjs compatible signing class

### ISSUE THREAD

**Issue by CodeForcer** [bitcoinjs/bitcoinjs-message#33]
For our frontend applications we use abstracted custom signers, to decouple private key handling logic from external packages, and to allow easy integration of third-party and external wallets.

With bitcoinjs library this works great, you can create a Bitcoin signer class and pass it wherever it needs to go, but this doesn't work with bitcoinjs-message.

Is it possible to add a feature to bitcoinjs-message so that a bitcoinjs compatible signer can be passed into the `sign` function, instead of the private key?

Thank you for the great package!

**Comment by junderw** [comment]
Great idea!

**Comment by junderw** [comment]
Please check Pull Request 34 and tell me if this is what you are looking for.

**Comment by CodeForcer** [comment]
@junderw I just checked and this works out-of-the-box with our signer setup now, thank you!

**Comment by junderw** [comment]
@CodeForcer Published as v2.2.0
