### ISSUE TITLE
Why +8 for segwit addresses in the recoverable ID bytes? Signatures don't verify in Electrum etc.

### ISSUE THREAD

**Issue by benma** [bitcoinjs/bitcoinjs-message#35]
Messages signed by this library for bech32 addresses can't be verified in Electrum and other libraries such as btcsuite.

I tracked it down to the fact that 8 is added to the recoverable ID byte:

https://github.com/bitcoinjs/bitcoinjs-message/blob/c43430f4c03c292c719e7801e425d887cbdf7464/index.js#L29

So far I expected the recoverable ID byte, minus 27 minus 4, to be in 0, 1, 2, or 3.

What is the purpose of this? This issue is for clarification, I didn't see this 8 offset anywhere before yet.

Thanks.

**Comment by junderw** [comment]
Since there's no BIP, everyone is all over the place.

This 8 is supported by Trezor.

Pull Requests are welcome.
