### ISSUE TITLE
Verify method returns true even after changing the base64 signature string

### ISSUE THREAD

**Issue by Rasika9596** [bitcoinjs/bitcoinjs-message#36]
Hello,

Why verify method returns true even after changing the signature char at the end?

I'm using the following code,

generate random key pair-

   ```
const bitcoin = require("bitcoinjs-lib");
     
    keyPair = bitcoin.ECPair.makeRandom();
    // get the private key
    const privateKey= keyPair.privateKey.toString("hex");
    // get the public key
    const publicKey = keyPair.publicKey.toString("hex");
   //// get the address from the public key

    // generate the sha256 of Public Key
    const pbSha256Digest = calculateSHA256(publicKey);

    // generate the ripemd-160 of the sha256 of the public key
    const pbRipemd160Digest = calculateRipemd160(pbSha256Digest);

    // prefix 0x00 to pbRipemd160Digest, 0x00 is the main network id
    const pbMainNetwork = "00" + pbRipemd160Digest;

    // ------ Below process is to calculate the address checksum
    // generate the sha256 of the pbMainNetwork
    const pbMNSha256Digest = calculateSHA256(pbMainNetwork);

    // generate the sha256 of pbMNSha256Digest to get the address checksum
    const pbSHA256AddressCheckSum = calculateSHA256(pbMNSha256Digest);

    // first 4 bytes of the pbSHA256AddressCheckSum is the address checksum
    const addressCheckSum = pbSHA256AddressCheckSum.slice(0, 8);

    // concat the address checksum to the pbMainNetwork. This is the 25-byte binary Bitcoin Address.
    const addressInBinary = pbMainNetwork + addressCheckSum;

    const addressBytes = Buffer.from(addressInBinary, "hex");

    // Convert the result from a byte string into a base58 string using Base58Check encoding.
    const address = bs58.encode(addressBytes); 

```
Sign message using private key and message -

```
    const keyPair = bitcoin.ECPair.fromPrivateKey(
      Buffer.from(privateKey, "hex")
    );
    // sign the message using the private key, convert it into base64 format 
    const  signMessage = bitcoinMessage
      .sign(message, keyPair.privateKey, keyPair.compressed)
      .toString("base64");
```
Verify message using below-

```
     const bitcoinMessage = require("bitcoinjs-message");
      isVerified = bitcoinMessage.verify(message, address, signature);
```
Using the above methods below is the generated data -

"privateKey": "9f4a91e71fd597976908fa07243ea96cd6f0f3e09f3652c5fab52570733575d7",
"publicKey": "02c478cc171b516f4890b71f60eb52d757cb5cb8d86fbc799935504d28072872d1",
"address": "1CTy3z89FBQ7MAkbindJEeSkXGsK1JRy6N"

"message":"Hello Bitcoin"
"Signature":"HyjpzUupgE5xNzRgCgFzXWzTbYhxFeu6txf1x4wMAgWVRMPM3DCrz99IX3pENwcGF5K1j7bG1pnqOaUPqR4tfVE="

In the end, I'm verifying the signature using the below data and its giving true response,
"message": "Hello Bitcoin",
"signature": "HyjpzUupgE5xNzRgCgFzXWzTbYhxFeu6txf1x4wMAgWVRMPM3DCrz99IX3pENwcGF5K1j7bG1pnqOaUPqR4tfVE=",
"address": "1CTy3z89FBQ7MAkbindJEeSkXGsK1JRy6N"

But even if changing the signature to below one also its giving true only,
HyjpzUupgE5xNzRgCgFzXWzTbYhxFeu6txf1x4wMAgWVRMPM3DCrz99IX3pENwcGF5K1j7bG1pnqOaUPqR4tfVE===
HyjpzUupgE5xNzRgCgFzXWzTbYhxFeu6txf1x4wMAgWVRMPM3DCrz99IX3pENwcGF5K1j7bG1pnqOaUPqR4tfVE

**Comment by junderw** [comment]
Your code does not show the issue.

Perhaps this is a misunderstanding of the flag byte? Similar to #18 ?

I can't tell, since your code does not show me the issue.

**Comment by Rasika9596** [comment]
As per the comments in #18 , this issue is resolved. Then could you please let me know why I'm facing this? What could be the issue with the above code?

**Comment by junderw** [comment]
= is optional padding, with or without it the encoded data is the same.

**Comment by Rasika9596** [comment]
With this, if I do the changes like below then also it's giving a true result. Is this because of same reason?

........ at the end or start 
///// at the end or start 
abc at the end
1234 at the end
at the start or end ##
^^^^, &&& , ***,((( in the mid of sign msg

**Comment by junderw** [comment]
That's how base64 decoding works. Your issue has nothing to do with this library.

```js
> Buffer.from('aGVsbG8=','base64').toString('utf8')
'hello'
> Buffer.from('aGVsbG8=.....','base64').toString('utf8')
'hello'
> Buffer.from('.....aGVsbG8=.....','base64').toString('utf8')
'hello'
> Buffer.from('aGV......sbG8=','base64').toString('utf8')
'hello'
> Buffer.from('aGVsbG8=abc','base64').toString('utf8')
'hello'
> Buffer.from('aGVsbG8=1234','base64').toString('utf8')
'hello'
```

**Comment by Rasika9596** [comment]
Oh. Thank You so Much for the details.
