### ISSUE TITLE
JS Browser version on a CDN

### ISSUE THREAD

**Issue by AlbinCauderlier** [bitcoinjs/bitcoinjs-message#40]
First of all, congratulations for this repository, which is, as far as I can search, the one with the most features.

I'm looking for a way to use it directly from a web page, in a js-browser way, in order to make signature verifications.
Moreover, it may be a way to use it in browser extensions.

I found the CDN of bitcoinjs-lib (currently : https://cdnjs.cloudflare.com/ajax/libs/bitcoinjs-lib/0.2.0/bitcoinjs-min.js), but I haven't found the same JS file for this repository.

Would you recommand that I create this js file through Browserify, or is it better if you publish an official version, and the updates?

By ahead, thank you for your help.

**Comment by junderw** [comment]
Do not trust that CDN. We have not uploaded any bundled JS to any CDN ever.

Please create the file yourself, and please use at least the latest v5.x.x instead of v0.2.0 (which is over 7 years old with tons of known bugs)

**Comment by AlbinCauderlier** [comment]
> Do not trust that CDN. We have not uploaded any bundled JS to any CDN ever.

Yes, I know you haven't, ... because this was my need.
This CDN link was just **an exemple** from what has been done by the **bitcoinjs/bitcoinjs-lib** team.


> Please use at least the latest v5.x.x instead of v0.2.0 (which is over 7 years old with tons of known bugs)

Yes, ... I would say "of course". v0.2.0 is regarding bitcoinjs-lib... not bitcoinjs-message... 


> Please create the file yourself.

Ok, I will... 
Thank you very much for your answer.
