### ISSUE TITLE
Add sign/verify for SegWit P2SH addresses

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-message#6]
> For TREZOR we implemented a way how to Sign and Verify SegWit P2SH addresses. This 
> is achieved by introducing extra `v` values used during signing.
> 
> Currently the following are used:
> 
> * 27-30 uncompressed pubkey (base58)
> * 31-34 compressed pubkey (base58)
> 
> We added the following:
> 
> * 35-38 p2sh segwit pubkey (base58)
> * 39-42 segwit pubkey (bech32)
> 
> [Unit tests for reference](https://github.com/trezor/python-trezor/blob/master/tests/device_tests/test_msg_signmessage_segwit.py)

Reference https://github.com/bitcoinjs/bitcoinjs-lib/issues/880

**Comment by dabura667** [comment]
is there a BIP that explains the original signature methodology???

I'm guessing not.

**Comment by dcousens** [comment]
@dabura667 I don't think so

**Comment by prusnak** [comment]
There was not a BIP describing the original method, so I did not create a BIP for new values. It would be nice to have one, though.

**Comment by EvilJordan** [comment]
Does this mean that the current release of bitcoinjs-message does or does not handle the signing/verifying of segwit addresses?

**Comment by dcousens** [comment]
@EvilJordan it does not handle it,  as it doesn't have community consensus.  PR's welcome though :+1:

**Comment by dcousens** [comment]
@prusnak I don't have time to implement the feature.
Happy to re-open if you or someone else intends to :+1:

**Comment by prusnak** [comment]
Fair enough :)
