### ISSUE TITLE
When signing with a given private key a given message, signature is always the same

### ISSUE THREAD

**Issue by Geam** [bitcoinjs/bitcoinjs-message#8]
Hello,
when I use this library to sign a given message with a given private key, the signature is always the same but I would like to have a different one each time.

When I look at the secp256k1 [sign function](https://github.com/cryptocoinjs/secp256k1-node/blob/master/API.md#signbuffer-message-buffer-privatekey--object-options---signature-buffer-recovery-number) there is an optionnal parameter taking either a nonce function or some data to obtain a different signature each time.

Is it possible to expose that optionnal parameter for the caller to put what he want in it ? Like
```javascript
function sign (message, privateKey, compressed, messagePrefix, options) {
  var hash = magicHash(message, messagePrefix)
  var sigObj = secp256k1.sign(hash, privateKey, options)
  return encodeSignature(sigObj.signature, sigObj.recovery, compressed)
}
```

EDIT : or could it be possible to have by default the randomness factor ? It can be as easy as
```javascript
var { randomBytes } = require("crypto");
[...]
function sign (message, privateKey, compressed, messagePrefix) {
  var hash = magicHash(message, messagePrefix)
  var sigObj = secp256k1.sign(hash, privateKey, {data: randomBytes(32)})
  return encodeSignature(sigObj.signature, sigObj.recovery)
}
```

**Comment by dcousens** [comment]
We would need to change this existing API to support this feature

**Comment by CleyFaye** [comment]
It seems that in some circumstances not having a random nonce can be an issue :
https://github.com/tintinweb/ecdsa-private-key-recovery
(I can't check the math so maybe I'm wrong).

Having an extra parameters seems fine to me: if no extra argument is provided, the current behavior is preserved. However I'm not sure if this is desirable if it poses a threat to private keys.

For the time being, would it be fine to just add the optional parameter to sign()? If so, I'll look into making a pull request for it.

**Comment by dabura667** [comment]
@CleyFaye No. The link you posted is FIXED by using the same k. In a very specific way known as RFC6979

The problem is when you use the same k *WITH DIFFERENT MESSAGES AND THE SAME PRIVATE KEY*

The way this library works, *A DIFFERENT MESSAGE WILL ALWAYS MEAN A DIFFERENT K* so it is impossible to use the same k (and thus the same r) with two different messages.

The reason why:

signatures are made up of r and s values.

```
r = (kG) x value mod n
s = k^-1(z + rp) mod n where z is message hash, p is private key, and r and k are from the r formula.

Case different messages, same private key, same k:
r and k are the same so we can forget the r equation, it gives us no new info.

so we have two s equations:
s1 = k^-1(z1 + rp) mod n
s2 = k^-1(z2 + rp) mod n
k, r, p are same... s and z are different.
subtract equations: (let's forget about mod n for a sec)
s1 - s2 = k^-1(z1 + rp) - k^-1(z2 + rp)
multiply both sides by k
k(s1 - s2) = z1 + rp - z2 - rp
+rp and -rp cancel out and divide both sides by s1 - s2
k = (z1 - z2) / (s1 - s2)

So using the same k (and thus the same r, which is visible in the signature) will let an outside observer calculate k.
with k, you can solve the s equation for p, since r, s, z are known and with k, now the only unknown is p.
```

**Comment by Geam** [comment]
Well, to be honest I don't really need a different signature each time, it's just that I recently change to bitcoinjs-message and I've realize that the signature was always the same. As I was searching why, I found that the `secp256k1` library had an optional parameter to generate a nonce and it was not used by bitcoinjs-message.

After a few test, I manage to obtain different signature each time (like I had before switching to this library) so I ask if it would be possible to expose the optional parameter to the caller so that if someone want to use that option, he could. Though after reading your answers (and a part of RFC6979), I understand that it is not needed.
